---
- name: Create Wallet for 0G Validator Node
  hosts: localhost
  become: true

  vars:
    GO_VERSION: "1.23.0"
    ALLOCHAIN_REPO: "https://github.com/allora-network/allora-chain.git"
    ALLORAD_VERSION: "HEAD-c1585f96b0ba2331bd408594d37e11a767e2fae0"

  vars_prompt:
    - name: wallet_name
      prompt: "Enter your wallet name"
      private: false

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install required packages
      apt:
        name:
          - curl
          - git
          - wget
          - build-essential
          - jq
          - pkg-config
          - lsb-release
          - libssl-dev
          - libreadline-dev
          - libffi-dev
          - gcc
          - unzip
          - lz4
          - python3
          - python3-pip
        state: present

    - name: Install Go
      shell: |
        cd $HOME && \
        ver="{{ GO_VERSION }}" && \
        wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz" && \
        rm -rf /usr/local/go && \
        tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz" && \
        rm "go$ver.linux-amd64.tar.gz"
      args:
        executable: /bin/bash

    - name: Update PATH permanently
      lineinfile:
        path: /etc/environment
        line: 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/root/go/bin"'
        regexp: '^PATH='
      become: yes

    - name: Add /root/go/bin to PATH permanently
      lineinfile:
        path: /etc/profile
        line: 'export PATH=$PATH:/root/go/bin'
        create: yes
      become: yes

    - name: Source /etc/environment and /etc/profile
      shell: |
        source /etc/environment
        source /etc/profile
      args:
        executable: /bin/bash

    - name: Clone Allora Chain repository
      git:
        repo: "{{ ALLOCHAIN_REPO }}"
        dest: "{{ ansible_env.HOME }}/allora-chain"
        version: "tags/v0.5.0"
        force: yes

    - name: Run make install for Allora Chain
      shell: |
        cd {{ ansible_env.HOME }}/allora-chain
        /usr/local/go/bin/go mod tidy
        PATH=$PATH:/usr/local/go/bin make install
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"

    - name: Ensure wallet directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.allorad/wallets"
        state: directory
        mode: '0755'

    - name: Add new wallet and store output
      ansible.builtin.shell: |
        /root/go/bin/allorad keys add {{ wallet_name }} --keyring-backend test --output json > {{ ansible_env.HOME }}/.allorad/wallets/{{ wallet_name }}.info
      args:
        executable: /bin/bash

    - name: Display wallet information message
      ansible.builtin.debug:
        msg: "Wallet created. You can find the wallet information, including the recovery phrase, in {{ ansible_env.HOME }}/.allorad/wallets/{{ wallet_name }}.info"

    - name: Add PATH export to .bashrc
      lineinfile:
        path: /root/.bashrc
        line: 'export PATH=$PATH:/root/go/bin'
        create: yes

    - name: Source .bashrc
      shell: source /root/.bashrc
      args:
        executable: /bin/bash

    - name: Display final message
      ansible.builtin.debug:
        msg: "Installation complete. Please log out and log back in, or run 'source ~/.bashrc' to use allorad command directly."