---
- name: Deploy Allora Validator Node using Ansible
  hosts: all
  become: true

  vars_prompt:
    - name: moniker
      prompt: "Enter your node name"
      private: false

  vars:
    NETWORK: allora-testnet-1
    GENESIS_URL: "https://raw.githubusercontent.com/allora-network/networks/main/{{ NETWORK }}/genesis.json"
    SEEDS_URL: "https://raw.githubusercontent.com/allora-network/networks/main/{{ NETWORK }}/seeds.txt"
    PEERS_URL: "https://raw.githubusercontent.com/allora-network/networks/main/{{ NETWORK }}/peers.txt"
    APP_HOME: "/root/.allorad"
    INIT_FLAG: "{{ APP_HOME }}/.initialized"
    KEYRING_BACKEND: test
    GENESIS_FILE: "{{ APP_HOME }}/config/genesis.json"
    DENOM: uallo
    SEEDS_FILE: "/tmp/seeds.txt"
    PEERS_FILE: "/tmp/peers.txt"
    GO_VERSION: "1.23.0"
    ADDRBOOK_URL: "https://snapshots.polkachu.com/testnet-addrbook/allora/addrbook.json"
    ADDRBOOK_FILE: "{{ APP_HOME }}/config/addrbook.json"
    SNAPSHOT_BASE_URL: "https://server-3.itrocket.net/testnet/allora/"
    #SNAPSHOT_REGEX: "allora_*.tar.lz4"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install required packages
      apt:
        name:
          - curl
          - git
          - jq
          - wget
          - build-essential
          - gcc
          - lz4
        state: present

    - name: Check if /usr/local/go exists
      stat:
        path: /usr/local/go
      register: go_directory

    - name: Remove /usr/local/go directory
      file:
        path: /usr/local/go
        state: absent
      when: go_directory.stat.exists

    - name: Download Go archive
      get_url:
        url: "https://golang.org/dl/go{{ GO_VERSION }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ GO_VERSION }}.linux-amd64.tar.gz"

    - name: Extract Go archive to /usr/local
      ansible.builtin.unarchive:
        src: "/tmp/go{{ GO_VERSION }}.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes

    - name: Clean up the downloaded Go archive
      file:
        path: "/tmp/go{{ GO_VERSION }}.linux-amd64.tar.gz"
        state: absent

    - name: Add Go to PATH in .bash_profile
      lineinfile:
        path: /root/.bash_profile
        line: 'export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin'
        create: yes

    - name: Source profile for Go
      shell: source /root/.bash_profile
      args:
        executable: /bin/bash

    - name: Verify Go installation
      command: /usr/local/go/bin/go version
      register: go_version

    - name: Print Go version
      debug:
        msg: "{{ go_version.stdout }}"

    - name: Clone Allora Chain repository
      git:
        repo: 'https://github.com/allora-network/allora-chain.git'
        dest: "{{ ansible_env.HOME }}/allora-chain"
        version: "tags/v0.4.0"
        force: yes

    - name: Run make install
      shell: |
        cd {{ ansible_env.HOME }}/allora-chain
        make install
        echo "export PATH=$PATH:{{ ansible_env.HOME }}/go/bin" >> {{ ansible_env.HOME }}/.bashrc
        source {{ ansible_env.HOME }}/.bashrc
        which allorad
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
      register: make_install_output

    - name: Display make install output
      debug:
        var: make_install_output.stdout_lines

    - name: Set fact for allorad path
      set_fact:
        allorad_path: "{{ make_install_output.stdout_lines[-1] }}"

    - name: Ensure APP_HOME directory exists
      file:
        path: "{{ APP_HOME }}"
        state: directory

    - name: Remove existing configuration if not initialized
      shell: rm -rf {{ APP_HOME }}/config
      when: not (INIT_FLAG | bool)

    - name: Initialize the node
      shell: |
        export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
        which allorad
        allorad --home {{ APP_HOME }} init {{ moniker }} --chain-id {{ NETWORK }} --default-denom {{ DENOM }}
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
      when: not (INIT_FLAG | bool)

    - name: Download genesis file
      get_url:
        url: "{{ GENESIS_URL }}"
        dest: "{{ GENESIS_FILE }}"
      when: not (INIT_FLAG | bool)

    - name: Configure allorad client
      shell: |
        source {{ ansible_env.HOME }}/.bashrc
        {{ allorad_path }} --home={{ APP_HOME }} config set client chain-id {{ NETWORK }}
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
      when: not (INIT_FLAG | bool)

    - name: Set keyring-backend for allorad client
      shell: |
        source {{ ansible_env.HOME }}/.bashrc
        {{ allorad_path }} --home={{ APP_HOME }} config set client keyring-backend {{ KEYRING_BACKEND }}
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
      when: not (INIT_FLAG | bool)

    - name: Create symlink for allorad config
      file:
        src: "{{ APP_HOME }}"
        dest: "{{ APP_HOME }}/.allorad"
        state: link
      when: not (INIT_FLAG | bool)

    - name: Create init flag
      file:
        path: "{{ INIT_FLAG }}"
        state: touch
      when: not (INIT_FLAG | bool)

    - name: Download seeds file
      get_url:
        url: "{{ SEEDS_URL }}"
        dest: "{{ SEEDS_FILE }}"

    - name: Read seeds from file
      slurp:
        src: "{{ SEEDS_FILE }}"
      register: seeds_content

    - name: Decode seeds content
      set_fact:
        seeds: "{{ seeds_content.content | b64decode }}"

    - name: Download peers file
      get_url:
        url: "{{ PEERS_URL }}"
        dest: "{{ PEERS_FILE }}"

    - name: Read peers from file
      slurp:
        src: "{{ PEERS_FILE }}"
      register: peers_content

    - name: Decode peers content
      set_fact:
        peers: "{{ peers_content.content | b64decode }}"    

    - name: Configure pruning to save storage
      ansible.builtin.shell: |
        sed -i \
            -e "s/^pruning *=.*/pruning = \"custom\"/" \
            -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"100\"/" \
            -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"0\"/" \
            -e "s/^pruning-interval *=.*/pruning-interval = \"10\"/" \
            "{{ APP_HOME }}/config/app.toml"
      args:
        executable: /bin/bash

    - name: Configure indexer to null
      ansible.builtin.shell: |
        sed -i "s/^indexer *=.*/indexer = \"null\"/" {{ APP_HOME }}/config/config.toml
      args:
        executable: /bin/bash

    - name: Change ports in config.toml
      ansible.builtin.shell: |
        sed -i "s/^laddr = \"tcp:\/\/0.0.0.0:26656\"/laddr = \"tcp:\/\/0.0.0.0:26666\"/" {{ APP_HOME }}/config/config.toml
        sed -i "s/^laddr = \"tcp:\/\/127.0.0.1:26657\"/laddr = \"tcp:\/\/127.0.0.1:26667\"/" {{ APP_HOME }}/config/config.toml
        sed -i "s/^pprof_laddr = \"localhost:6060\"/pprof_laddr = \"localhost:6061\"/" {{ APP_HOME }}/config/config.toml
      args:
        executable: /bin/bash

    - name: Change port in client.toml
      ansible.builtin.shell: |
        sed -i "s/^node = \"tcp:\/\/localhost:26657\"/node = \"tcp:\/\/localhost:26667\"/" {{ APP_HOME }}/config/client.toml
      args:
        executable: /bin/bash

    - name: Download addrbook.json
      get_url:
        url: "{{ ADDRBOOK_URL }}"
        dest: "{{ ADDRBOOK_FILE }}"

    - name: Create systemd service file from template
      template:
        src: templates/allora-validator-node.service.yml.j2
        dest: /etc/systemd/system/allora-node.service
      vars:
        app_home: "{{ APP_HOME }}"
        moniker: "{{ moniker }}"
        denom: "{{ DENOM }}"
        seeds: "{{ seeds }}"
        peers: "{{ peers }}"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Enable and start Allora Node service
      systemd:
        name: allora-node
        enabled: true
        state: stopped
        daemon_reload: yes
        
  
    - name: Get latest snapshot filename
      uri:
        url: "{{ SNAPSHOT_BASE_URL }}"
        return_content: yes
      register: snapshot_page

    - name: Extract all snapshot filenames
      set_fact:
        all_snapshots: "{{ snapshot_page.content | regex_findall('allora_\\d{4}-\\d{2}-\\d{2}_\\d+_snap\\.tar\\.lz4') }}"

    - name: Sort snapshots and get the latest
      set_fact:
        snapshot_filename: "{{ all_snapshots | sort | last }}"

    - name: Display snapshot filename
      debug:
        msg: "Downloading snapshot: {{ snapshot_filename }}"

    - name: Download snapshot
      get_url:
        url: "{{ SNAPSHOT_BASE_URL }}{{ snapshot_filename }}"
        dest: "/root/{{ snapshot_filename }}"
      register: download_result

    - name: Show download result
      debug:
        var: download_result


    - name: Reset the Node
      command: allorad comet unsafe-reset-all --keep-addr-book
      environment:
          PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"    

    - name: Install pv
      apt:
        name: pv
        state: present           

    - name: Extract the Snapshot
      shell: |
        pv /root/{{ snapshot_filename }} | lz4 -cd | tar -x -C {{ APP_HOME }}
      args:
        executable: /bin/bash
      register: extract_output

    - name: Display extraction progress
      debug:
        msg: "{{ extract_output.stdout_lines }}"

    - name: Check if priv_validator_state.json exists
      stat:
        path: "{{ APP_HOME }}/priv_validator_state.json"
      register: priv_validator_state

    - name: Restore priv_validator_state.json if it exists
      copy:
        src: "{{ APP_HOME }}/priv_validator_state.json"
        dest: "{{ APP_HOME }}/data/priv_validator_state.json"
        remote_src: yes
      when: priv_validator_state.stat.exists


    - name: Verify snapshot extraction
      stat:
        path: "{{ APP_HOME }}/data"
      register: data_dir

    - name: Show extraction result
      debug:
        msg: "Snapshot extracted successfully: {{ data_dir.stat.exists }}"    

    - name: Clean Up snapshot file
      file:
        path: "/root/{{ snapshot_filename }}"
        state: absent


