---
- name: Remove Allora Validator Node
  hosts: localhost
  become: true

  tasks:
    - name: Stop Allora Validator Node service
      ansible.builtin.systemd:
        name: allora-node
        state: stopped
        enabled: false
      ignore_errors: true

    #- name: Kill any remaining Allora Validator Node processes
    #  ansible.builtin.shell: |
    #    pkill -f allorad
    #  ignore_errors: true

    - name: Wait for any remaining processes to terminate
      ansible.builtin.wait_for:
        timeout: 10

    - name: Remove Allora Validator Node service file
      ansible.builtin.file:
        path: /etc/systemd/system/allora-node.service
        state: absent
      ignore_errors: true

    - name: Remove Allora Validator Node state directory
      ansible.builtin.shell: |
        rm -rf /run/systemd/system/allora-node.service
        rm -rf /etc/systemd/system/allora-node.service
      ignore_errors: true

    - name: Remove Allora Validator Node data directory
      ansible.builtin.file:
        path: "/root/.allorad"
        state: absent
      ignore_errors: true

    - name: Remove Allora Chain repository
      ansible.builtin.file:
        path: "/root/allora-chain"
        state: absent
      ignore_errors: true

    - name: Remove allorad binary from /root/go/bin
      ansible.builtin.file:
        path: /root/go/bin/allorad
        state: absent
      ignore_errors: true

    - name: Remove allorad binary from /root/.local/bin
      ansible.builtin.file:
        path: /root/.local/bin/allorad
        state: absent
      ignore_errors: true

    - name: Remove Go binary directory
      ansible.builtin.file:
        path: /usr/local/go
        state: absent
      ignore_errors: true

    - name: Remove Go workspace directory
      ansible.builtin.file:
        path: /root/go
        state: absent
      ignore_errors: true

    - name: Remove Go bin from PATH in .profile
      lineinfile:
        path: /root/.profile
        regexp: 'export PATH=\$PATH:/usr/local/go/bin'
        state: absent
      ignore_errors: true

    - name: Remove allora bin from PATH in .profile
      lineinfile:
        path: /root/.profile
        regexp: 'export PATH=\$PATH=/root/.local/bin'
        state: absent
      ignore_errors: true

    - name: Remove all Go environment variables from .profile
      lineinfile:
        path: /root/.profile
        regexp: 'export GOPATH=\$HOME/go'
        state: absent
      ignore_errors: true

    - name: Reload .profile
      shell: source /root/.profile
      ignore_errors: true

    - name: Reload systemd to apply changes
      ansible.builtin.shell: |
        systemctl daemon-reload
        systemctl reset-failed
      ignore_errors: true

    - name: Display message
      ansible.builtin.debug:
        msg: "Allora Validator Node and Go have been removed successfully."
