---
- name: Remove Allora Worker Node
  hosts: localhost
  become: true

  vars:
    HF_REPO_DIR: "/root/allora-huggingface-walkthrough"
    DOCKER_COMPOSE_PATH: "/usr/local/bin/docker-compose"

  tasks:
    - name: Stop Allora Worker service
      ansible.builtin.systemd:
        name: allora-worker
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Wait for any remaining processes to terminate
      ansible.builtin.wait_for:
        timeout: 30

    - name: Remove Allora Worker service file
      ansible.builtin.file:
        path: /etc/systemd/system/allora-worker.service
        state: absent
      ignore_errors: true

    - name: Remove Hugging Face repository
      ansible.builtin.file:
        path: "{{ HF_REPO_DIR }}"
        state: absent
      ignore_errors: true

    - name: Remove Docker containers and images
      ansible.builtin.shell: |
        cd {{ HF_REPO_DIR }}
        docker-compose down --rmi all --volumes --remove-orphans
        docker system prune -af
      ignore_errors: true

    - name: Remove Docker Compose binary
      ansible.builtin.file:
        path: "{{ DOCKER_COMPOSE_PATH }}"
        state: absent
      ignore_errors: true

    - name: Reload systemd to apply changes
      ansible.builtin.shell: |
        systemctl daemon-reload
        systemctl reset-failed
      ignore_errors: true

    - name: Display message
      ansible.builtin.debug:
        msg: "Allora Worker Node has been removed successfully."