FROM amd64/python:3.9-buster

WORKDIR /app

COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip cache purge

EXPOSE 8000

ENV NAME sample

# Run the Flask app directly instead of using gunicorn
CMD ["python", "-u", "/app/app_chronos.py"]